### ISSUE TITLE
SV_COMP Benchmark test report

### ISSUE THREAD

**Issue by tnkhanh** [sbip-sg/discover#46]
Bugs are correctly detected in the following files:
```
PostfixIncrement.c (x=maxInt; x++)
PrefixIncrement.c (x=maxInt; ++x)
UnaryMinus.c (y=-minInt)
```
Discover did not detect bugs in these files, might need some fix:
```llvm
AdditionIntMax.c (constant folding was used)
AdditionIntMin.c (minInt + -1 + 23)
   %v1 = add nsw i32 -2147483648, -1, !dbg !15
   %v2 = add nsw i32 %v1, 23, !dbg !16
Division-1.c (minInt / -1)
   %v1 = sdiv i32 -2147483648, -1, !dbg !15
   %v2 = sub nsw i32 %v1, 1, !dbg !16
Multiplication-2.c (constant folding)
NoConversion.c (probably constant folding)
PostfixDecrement.c (x=minInt; x--)
  %v1 = add nsw i32 -2147483648, -1, !dbg !15
PrefixDecrement.c (x=minInt; --x)
  %v1 = add nsw i32 -2147483648, -1, !dbg !15
UsualArithmeticConversions.c (no bug here, but constant folding was used)
```
All samples without bugs are good. Discover reports there are no bug there (maybe just a coincidence).

**Comment by taquangtrung** [comment]
@tnkhanh: noted! Can you help to investigate and fix the test cases that Discover failed to detect bugs?

**Comment by tnkhanh** [comment]
I fixed a minor code typo and Discover can detect most bugs in the benchmarks now. I adjusted the tests to avoid constant folding.

Now there is only one file it cannot detect bugs: `Division-1.c`:
```c++
int main() {
	int minInt = -2147483647 - 1;
	int x = /*@{Bug:IntegerOverflow*/(minInt / -1 )/*@:Bug}*/ - 1;
	printf("%d\n", x);
	return 0;
}
```
Its IR is as follows:
```llvm
   Function: i32 main()
    bb0:
     call void @llvm.dbg.value(metadata i32 -2147483648, metadata !13, metadata !DIExpression()), !dbg !14
     %v1 = sdiv i32 -2147483648, -1, !dbg !15
     %v2 = sub nsw i32 %v1, 1, !dbg !16
     call void @llvm.dbg.value(metadata i32 %v2, metadata !17, metadata !DIExpression()), !dbg !14
     %v3 = getelementptr inbounds [4 x i8], [4 x i8]* @g0, i64 0, i64 0, !dbg !18
     %v4 = call i32 (i8*, ...) @printf(i8* %v3, i32 %v2), !dbg !18
     ret i32 0, !dbg !19
```

**Comment by taquangtrung** [comment]
@tnkhanh: thanks for the update!

Have you debugged why Discover cannot detect bug in the above test case?

**Comment by tnkhanh** [comment]
> 

Ah, not yet. I can work on that!
For now, the overflow variable `%v1` does not show any range in the analysis:
```llvm
 %v1 = sdiv i32 -2147483648, -1, !dbg !15

    []
```

**Comment by taquangtrung** [comment]
@tnkhanh : this is because the Div statement isn't supported yet:

https://github.com/sbip-sg/discover/blob/8200ee09e3d5e4785c156f8477b7874aeaba73a0/src/dataflow/range.ml#L779

We need to implement for that one
