### ISSUE TITLE
Find benchmarks of integer bugs

### ISSUE THREAD

**Issue by taquangtrung** [sbip-sg/discover#5]
**Focus on:** 
- C/C++: @taquangtrung 
- Solidity: @taquangtrung 
- Golang: @tnkhanh, @taquangtrung 
- Typescript

**Comment by taquangtrung** [comment]
@tnkhanh : can you find benchmarks of integer bugs in Golang?

**Comment by tnkhanh** [comment]
> @tnkhanh : can you find benchmarks of integer bugs in Golang?

Yes, I can do that

**Comment by taquangtrung** [comment]
> > @tnkhanh : can you find benchmarks of integer bugs in Golang?
> 
> Yes, I can do that.
> I need to know what is integer bug and how to find benchmarks first
Example of integer bugs:

-   Integer_overflow,
-   Integer_underflow,
-   Integer_unsafe_downcast,
-   Integer_division_by_zero

**Comment by tnkhanh** [comment]
I see. I will look into it.

**Comment by taquangtrung** [comment]
Use Juliet tests: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/tree/main/c/Juliet_Test/Juliet_Test_Suite_v1.3_for_C_Cpp/C/testcases
