### ISSUE TITLE
Discover incorrectly reports bugs since Store instruction is not yet implemented in range analysis

### ISSUE THREAD

**Issue by tnkhanh** [sbip-sg/discover#80]
Discover will incorrectly report a bug in the following code because `c=b+2` loads `b` which has the wrong range:
```c++
#include <stdio.h>
int main() {
  int a, b, c;
  scanf("%d%d%d", &a, &b, &c);
  a = 1000;
  b = a + 2;
  c = b + 2;
  return 0;
}
```
Interestingly, if there is no `scanf`, there will be no actual `alloca` or `store` or `load` involved and no bug reported.
It looks like we need to implement the `store` and `load` instruction for range analysis. Each pointer needs to record the range of its variable.

Output log for reference
[s7_with_scanf_incorrect.log](https://github.com/sbip-sg/discover/files/7702042/s7_with_scanf_incorrect.log)

**Comment by taquangtrung** [comment]
Currently the range value isn't updated on handling the `store` instruction.

```
  %v7 = add nsw i32 1000, 2
    [v7: [1002, 1002]]
  store i32 %v7, i32* %v2, align 4
    [v7: [1002, 1002]]
  %v8 = load i32, i32* %v2, align 4
    [v8: [-1 * 2^31 + 0, 1 * 2^31 + -1], v7: [1002, 1002]]
```

I'm investing it...

**Comment by taquangtrung** [comment]
Resolved in: https://github.com/sbip-sg/discover/commit/cd5e77d362e392bcfee39ead427f87ba9a4d6b27
